name: Template Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-generation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Test template generation
      run: |
        echo -e "test-project\nTest FAQ Site\nTest description\n\npurple\nn" | node setup-new-site.js
        
    - name: Test build
      run: npm run build
      
    - name: Test site functionality
      run: npm run dev &
